dist: trusty
sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  apt_packages:
    - pandoc
install:
  - python setup.py install
  - python setup.py sdist bdist_wheel
script:
  - py.test
deploy:
  - provider: pypi
    user: dhimmel
    password:
      secure: DG8uk3jcTfy6veFO7G0EpSK6KzCsCJV05dyOj/gixuZ6POJLEfOeDO97AIO1JMwZCcSfEoHQrY/udOqmh45sMShEW/CICDo4a+BkQl/7XbnNa7sul7Gz16HugkRdAG2SmqGY8ZTUnawdfn6HAnSojhduZ1xKpoxQNXwfExt/YOHKaj4c9jdknmX4m+Y6FitciA/l3Bbd98VpAvIs8rdJvSQHVKSHLXKwKLjJUF+LeWaL663sxmKJo1LcH99b805UIbf8eIpPTcY2j/sZTIavrbhSpllF864GS260yLWdSsjP/yhGtmiHrPKdlFInwoVlPMMmbrQkkocSmgLnnOe9lXekOrb7bRbE/BB3n6Q1GQWoBROLkMuQW+uP3AU9pAx9Md4b7BSkvsvRANaJrASXGxqJT5fYGjWIj4A43Giq6nhzH2wVfBpC9Qovp12mrZ0O8AS8np0FYmyJhFxc1upfA5js8UbEeHq6Kf46ka6pWaWUZG/nRr2cEXGvekbNDeXhirzNYCl+h/SLpva9iCHW3KBc+9qUKujueba63kty0j4UsS6Tfqw12r5/WNfPbQ0OxFNBBQRpFN08jmQ2kFTbFEscLgPlaxezuZ4JVOqDenWElG+no2mdiTB+o27DJHxQQnrL9XTKJgDNYSohzW19dPOtBq5bJT5L7J2ZehqMNj8=
    on:
      python: '3.6'
      repo: dhimmel/obonet
      tags: true
      distributions: sdist bdist_wheel
      branch: deploy
